version: '3.0'

services:

  duniter:
    image: duniter/duniter
    restart: always
    volumes:
      - ./data:/var/lib/duniter
    environment:
      - VIRTUAL_HOST=duniter.g1.pfouque.xyz # Enviroment variable needed for nginx proxy
      - LETSENCRYPT_HOST=duniter.g1.pfouque.xyz # Enviroment variables needed for Let's Encrypt companion
      - LETSENCRYPT_EMAIL=pfouque@gmail.com
    networks:
      - nginx-proxy
    ports:
      - "9220:9220" # web api port
      - "10901:80" # external host exposure -> webproxy incoming port 
      # - "10901" # BMA port withou webproxy
      - "20901:20901" # W2SP port

networks:
  nginx-proxy:
    external:
      name: webproxy_nginx-proxy # Reference webproxy/nginx-proxy container network
