version: '3.0'
# t!!!! his version is failing because external volume binding is not operational

services:

  duniter:
    image: duniter/duniter
    restart: always # unless_stopped for non production nodes
    volumes:
      - data:/var/lib/duniter
    ports:
      - "9220:9220"
      - "10901:10901"
      - "20901:20901"

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data #settings failing !