version: '3.0'

services:

  duniter:
    image: duniter/duniter
    restart: always # 'unless_stopped' for non production nodes, 'always' for production nodes
    volumes:
      - ./data:/var/lib/duniter
      - ./keychain:/etc/duniter
    ports:
      - "9220:9220"
      - "10901:10901"
      - "20901:20901"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"