version: '3.0'

services:

  duniter:
    image: duniter/duniter
    restart: always
    volumes:
      - ./data:/var/lib/duniter
    ports:
      - "9220:9220"
      - "10901:10901"
      - "20901:20901"